// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG1ZISNTNRWR1-2mwkGBWaDssGAJ_kvEc',
    appId: '1:964732214398:web:5e5071a188d64a56d24c2f',
    messagingSenderId: '964732214398',
    projectId: 'bee-smiley-admin',
    authDomain: 'bee-smiley-admin.firebaseapp.com',
    storageBucket: 'bee-smiley-admin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD34ChRiP2ozUNUENeDJQfDj3kdcVa9WDo',
    appId: '1:964732214398:android:788ec45ec662bbf1d24c2f',
    messagingSenderId: '964732214398',
    projectId: 'bee-smiley-admin',
    storageBucket: 'bee-smiley-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6q_tIIgCiVLtvl6dult3x2dDaCTUwdJM',
    appId: '1:964732214398:ios:1723b80dda9e064ed24c2f',
    messagingSenderId: '964732214398',
    projectId: 'bee-smiley-admin',
    storageBucket: 'bee-smiley-admin.firebasestorage.app',
    iosBundleId: 'com.example.beeSmileyAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6q_tIIgCiVLtvl6dult3x2dDaCTUwdJM',
    appId: '1:964732214398:ios:1723b80dda9e064ed24c2f',
    messagingSenderId: '964732214398',
    projectId: 'bee-smiley-admin',
    storageBucket: 'bee-smiley-admin.firebasestorage.app',
    iosBundleId: 'com.example.beeSmileyAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG1ZISNTNRWR1-2mwkGBWaDssGAJ_kvEc',
    appId: '1:964732214398:web:305990f13d966662d24c2f',
    messagingSenderId: '964732214398',
    projectId: 'bee-smiley-admin',
    authDomain: 'bee-smiley-admin.firebaseapp.com',
    storageBucket: 'bee-smiley-admin.firebasestorage.app',
  );
}
